#************************** MDIS4 device descriptor *************************
#
# m99_sw_min.dsc: Descriptor for M99
# Automatically generated by mdiswiz 0.97a.003-linux-1 from 13m09906.xml
# 2004-05-04
#
#****************************************************************************

M99_SW_1 {

    # ------------------------------------------------------------------------
    #        general parameters (don't modify)
    # ------------------------------------------------------------------------
    DESC_TYPE = U_INT32 0x1
    HW_TYPE = STRING M99_sw

    # ------------------------------------------------------------------------
    #        reference to base board
    # ------------------------------------------------------------------------
    BOARD_NAME = STRING A12_1
    DEVICE_SLOT = U_INT32 0x0

    # ------------------------------------------------------------------------
    #        device parameters
    # ------------------------------------------------------------------------

    # Define wether M-Module ID-PROM is checked, don't enable for M99, works only once after power up
    # 0 := disable -- ignore IDPROM
    # 1 := enable
    ID_CHECK = U_INT32 0
}
# EOF
